### ISSUE TITLE
ModuleNotFoundError: No module named 'loguru'

### ISSUE THREAD

**Issue by AlRlC** [aqualxx/stable-horde-notebook#7]
```
/content/nataili
Traceback (most recent call last):
  File "bridge.py", line 8, in <module>
    from nataili.model_manager import ModelManager
  File "/content/nataili/nataili/__init__.py", line 1, in <module>
    from .util.switch import Switch
  File "/content/nataili/nataili/util/__init__.py", line 1, in <module>
    from nataili.util.logger import logger, quiesce_logger, set_logger_verbosity, test_logger
  File "/content/nataili/nataili/util/logger.py", line 4, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
```

https://cdn.discordapp.com/attachments/1056653011990089729/1056657328310591558/image.png

error is fixed after adding `!pip install loguru` to the `Install dependencies` cell

https://discord.com/channels/781145214752129095/1056653011990089729/1056665678570074213

**Comment by AlRlC** [comment]
https://github.com/aqualxx/stable-horde-notebook/pull/8

**Comment by aqualxx** [comment]
Thank you! Closing as I've merged your pull request.
